#!/bin/sh
read oldrev newrev _branch

REPO=$(basename "$PWD")
TARGET_BRANCHES="^(master|release-*|patch-*)"
branch=$(echo $_branch | sed 's/.*\/\([a-z0-9][a-z0-9]*\)$/\1/')
msg=$(git log -1 --pretty=format:"CommitDate: %ci%nRepo: ${REPO}%nBranch: ${branch}%nCommitHash: %h%nCommitter: %cn%nCommitMsg:%n%B" $newrev)


if [ "$branch" = "master" ] || [ "$branch" = "stage" ]
then
  curl -H "Content-Type: application/json; charset=utf-8" \
    -X POST \
    -d "{\"text\": \"${msg}\"}" \
    https://hooks.slack.com/services/TF...
fi
~