#!/bin/sh
# Prevents force-pushing to master

#BRANCH=`git rev-parse --abbrev-ref HEAD`
PUSH_COMMAND=`ps -ocommand= -p $PPID`
PROTECTED_BRANCHES="^(master|release-*|patch-*)"
FORCE_PUSH="force|delete|-f"
BRANCH=$(git rev-parse --symbolic --abbrev-ref $1)

if [[ "$BRANCH" =~ $PROTECTED_BRANCHES && "$USER" != 'admin' ]]
then
  echo "$USER is prevented to push $BRANCH branch"
  exit 1
fi

#if [[ "$BRANCH" =~ $PROTECTED_BRANCHES && "$PUSH_COMMAND" =~ $FORCE_PUSH ]]; then
#  echo "Prevented force-push to protected branch \"$BRANCH\" by pre-push hook"
#  exit 1
#fi

exit 0